FROM debian:13-slim

ARG application_version
LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL description="moosefs-cli image"
LABEL version=${application_version}

RUN apt update && \
    apt install -y apt-utils ca-certificates --no-install-recommends
RUN update-ca-certificates

RUN apt install -y moosefs-cli

CMD ["bash", "-l"]
