FROM debian:13-slim

ARG application_version
LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL version=${application_version}

RUN apt update && \
    apt install -y apt-utils ca-certificates --no-install-recommends
RUN update-ca-certificates

RUN apt install -y moosefs-chunkserver
LABEL description="moosefs-chunkserver image"

CMD ["/usr/sbin/mfschunkserver", "start"]
