FROM unixorn/moosefs-base

ARG application_version
LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL description="moosefs-cli image"
LABEL version=${application_version}

RUN apt install -y moosefs-cli

CMD ["bash", "-l"]
