FROM unixorn/moosefs-base

ARG application_version
LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL version=${application_version}

RUN apt-get install -y moosefs-metalogger

LABEL description="moosefs-metalogger image"
CMD ["/usr/sbin/mfsmetalogger", "start"]
