FROM unixorn/moosefs-base

ARG application_version
LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL description="moosefs-netdump image"
LABEL version=${application_version}

RUN apt-get install -y moosefs-netdump

CMD ["bash", "-l"]
