FROM unixorn/moosefs-base

ARG application_version
LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL version=${application_version}

RUN apt install -y moosefs-chunkserver
LABEL description="moosefs-chunkserver image"

CMD ["/usr/sbin/mfschunkserver", "start"]
