FROM unixorn/moosefs-base

ARG application_version
LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL version=${application_version}

RUN apt install -y moosefs-master
LABEL description="moosefs-master image"

CMD ["/usr/sbin/mfsmaster", "start"]
