FROM unixorn/moosefs-base

ARG application_version
LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL version=${application_version}

RUN apt install -y moosefs-cgiserv
LABEL description="moosefs-cgiserv image"

CMD ["/usr/sbin/mfscgiserv", "start"]
